[package]
name = "parsefile"
version = "0.1.0"
edition = "2024"

[lib]
name = "parsefile_lib"

[dependencies]
chardet = "0.2.4"
chrono = "0.4.42"
encoding = "0.2.33"
regex = "1.12.2"
rust_xlsxwriter = "0.92.2"
